export const skills: Record<string, string[]> = {
  "Product": [
    "Agile PM",
    "Lean Six Sigma",
    "User Research",
    "Roadmapping",
    "Stakeholder Management",
    "Technical Product Management",
    "AI Prompt Engineering",
    "Storytelling & Presentations",
    "Product Design",
    "Market Research",
  ],
  "Technical": [
    "SQL",
    "Python",
    "R",
    "JavaScript",
    "TypeScript",
    "React JS",
    "React Native",
    "Node.js",
    "AWS",
    "Expo",
    "Expo Router",
    "Docker",
    "SCSS",
    "Google Sheets API",
    "Google OAuth",
    "AsyncStorage",
    "expo-secure-store",
    "xlsx",
    "Claude API",
    "OpenAI API",
    "Gemini API",
    "Cloud Migration",
  ],
  "Tools": [
    "Jira",
    "Confluence",
    "Figma",
    "Adobe XD",
  ],
  "Certifications": [
    "Lean Six Sigma Green Belt",
    "Lean Six Sigma Yellow Belt",
    "Process Management Foundational Training",
    "Critical Business Processes Manager",
  ],
};